language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
script:
  - yarn lint
  - yarn jest -- --coverage
  - yarn test:coverage

after_success: yarn coveralls

before_deploy: ./internals/ci/increment-version.sh

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      branch: v1

after_deply: git push && git push --tags