language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - "node_modules"
    - "website/node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn check

  - yarn build

  - yarn lint
  - yarn test:coverage:report
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test:e2e; fi

  - yarn docs:build

after_success:
  - yarn audit
  - yarn coveralls

before_deploy: |
  # Handle release version number for NPM.

  # Only run before_deploy once.
  if ! [[ "$BEFORE_DEPLOY_RUN" ]]; then
    export BEFORE_DEPLOY_RUN=1
  else
    exit 0
  fi

  # Retrieve current version.
  PACKAGE_VERSION=$(node -p "require('./package.json').version")

  LATEST_VERSION=$(npm view twitch-js@$PACKAGE_VERSION)

  # If this version is unreleased ...
  if [[ ${#LATEST_VERSION} -eq "0" ]]; then
    # ... tag current version.
    git tag \
      --annotate v${PACKAGE_VERSION} \
      --message "v${PACKAGE_VERSION} release"
  else
    # ... otherwise, determine next version.
    if [[ $PACKAGE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      # Regular versions get a 'pre' version tag.
      NEXT_VERSION=`$(npm bin)/semver \
        $PACKAGE_VERSION \
        --increment prerelease \
        --preid pre`
    else
      # Prerelease versions retain version tag.
      NEXT_VERSION=`$(npm bin)/semver $PACKAGE_VERSION --increment prerelease`
    fi

    # Incrememnt version and append [ci skip] to the commit message to prevent
    # Travis CI from proccessing this build.
    npm version $NEXT_VERSION --message "v$NEXT_VERSION [ci skip]"
  fi

  # Build website.

  # Retrieve website source.
  curl -sL https://github.com/twitch-devs/twitch-js-docs/archive/ffac6be7cc5d28fabf347b5ad90b8ce75da68b43.tar.gz | tar xz --strip 1 */docs */website
  (cd website && yarn install && yarn build)


deploy:
  # Deploy v1.
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      branch: master
  # Deploy v2.
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    tag: next
    on:
      branch: next
  # Deploy website.
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: website/build/twitch-js
    on:
      branch: next

after_deploy: |
  # Only run after_deploy once.
  if ! [[ "$AFTER_DEPLOY_RUN" ]]; then
    export AFTER_DEPLOY_RUN=1
  else
    exit 0
  fi

  # Update version.
  git push --follow-tags https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG HEAD:$TRAVIS_BRANCH

  # Report coverage.
  yarn test:coverage:report