name: CI

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check integrity
        run: yarn check --integrity

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check style
        run: yarn prettier
      - name: Lint codebase
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: yarn test:coverage:report
      - name: Report coverage
        run: yarn coveralls

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn build

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit dependencies
        run: yarn audit
