name: CI

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

env:
  CODECOV_TOKEN: d812df45-0029-4c01-9a11-8aabd8b1a04b

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Check integrity
        run: yarn check --integrity

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Check style
        run: yarn prettier
      - name: Lint codebase
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests and report coverage
        run: yarn test:coverage:report

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Audit dependencies
        run: yarn audit --level low
